### PR TITLE
Revert orientation based icons due to side effects, fixes #20

### LINKED ISSUE #16: Entity.direction based icons and Logistic chests.
Started some work on Changing the icons from create/destroy to direction based. I am still working on tweaking it some but if you want to check out what I have so far https://github.com/Nexela/Bottleneck/tree/icons.

Amazingly (because factorio). creating/destroying doesn't add as much overhead as one would think. This switch gained about a .08/tick improvement in the heavily modded test base I am using.

It uses a storage-tank entity as this is the only one I could find that supported rotation. And I couldn't find anything that supported 8x rotation after placing. So switching to high-contrast mode is something that needs some thinking on.  Also I have some ideas on more speed improvements that will be needed for logistic chest bottlenecks I am working on.

### LINKED ISSUE #20: my bottlenecks turned into vehicles
i can get inside of the little balls and they are being moved around by transport belts. They also appear on the map as vehicles. The latest update broke them somehow.

### PR DESCRIPTION
**Pull request by Nexela**
Use direction based icons, closes #16
Better logic checking on signals, signals now rebuild if needed.
Allow specifying a custom offset when creating.
Remote.call to Get the Signal data for an entity if exists.
Should be better optimized now.
Increment Version number

### CODE REVIEW

**Comment by troelsbjerre** [comment]
This fixed the main bug from 0.6.0, but now the high contrast mode is broken.

**Comment by Nexela** [comment]
High contrast should be working, I tested it extensively, what is it doing? or not doing.

**Comment by Nexela** [comment]
Ok I know what happened give me about 10 minutes

**Comment by Nexela** [comment]
Should be all set in the latest request, my extensive tested included around 100 furnaces at 60/per tick  hence why I missed the halfsie issue.  Also removed a debug message that got left in.

**Pull request merged**
