### PR TITLE
Adjust the dots for usability

### PR DESCRIPTION
**Pull request by mybuddymichael**
### `master`
How the dots look on master

### This Branch
How the dots look on this branch

### Details
This branch adjusts the icons to make them more slightly more usable at a glance.

* The SVGs have been redrawn to increase the contrast between dots of different colors, as well as to increase the contrast between the dots and their icons.
* The icons have been made slightly bigger.
* The colors have been adjusted slightly be more readable.

### CODE REVIEW

**Comment by troelsbjerre** [comment]
Good job. Looks much clearer. However, I can see why some people would prefer the existing graphics, so overwriting the existing is not a good option. The new graphics could be added as an alternative graphics set, just like with the small version of the signals.

**Comment by mybuddymichael** [comment]
Thanks for considering this!

If you have a second, can you expand on why people might prefer the existing graphics so I can consider how to best accommodate those folks?

**Comment by Nexela** [comment]
> If you have a second, can you expand on why people might prefer the existing graphics so I can consider how to best accommodate those folks?

People hate change :)

**Comment by Roang-zero1** [comment]
Goes to show I should not be a graphics designer, I really like the improved look!

**Comment by Roang-zero1** [comment]
It would be easy to merge the new items into the options.
All you have to do is keep the current icons. Add the new ones with a different name (e.g. altert-flat) and add them to the prototypes in https://github.com/troelsbjerre/Bottleneck/blob/master/data.lua#L60-L66 .

**Comment by Roang-zero1** [comment]
Changes with both icon sets available at: https://github.com/Roang-zero1/Bottleneck/tree/adjust-icons

**Comment by mybuddymichael** [comment]
Just FYI, I haven't tested the new colors with the existing graphics.

**Comment by Roang-zero1** [comment]
> Just FYI, I haven't tested the new colors with the existing graphics.

I've tried them for a short while and the old items also look clearer with the new colors.

**Pull request merged**
