### PR TITLE
Set update_index when toggling highcontrast, Remove debug print

### PR DESCRIPTION
**Pull request by Nexela**

### CODE REVIEW

**Comment by Nexela** [comment]
Give me about 5 minutes to investigate the can't squeak through thing.

**Comment by Nexela** [comment]
Ok I can't find any issues with/without squeak through, I think the post may have been related to the 6.0 version.

**Comment by troelsbjerre** [comment]
I haven't tried with the squeak through mod, but with storage-tanks as lights, I cannot walk between assemblers with one atop the other, when there is a light "in between".

**Comment by Nexela** [comment]
Weirdest thing ever... but I have an idea

**Comment by troelsbjerre** [comment]
I tried a few things, but I really have no idea what I am doing...

**Pull request merged**
