### PR TITLE
Feat 0.17api - Rendering and entity.status

### PR DESCRIPTION
**Pull request by Roang-zero1**
As mentioned in #52 I've updated the code to use the new 0.17 rendering engine.

I've also rebased the branch on master to include the latest fixes, just fyi.

### CODE REVIEW

**Comment by Roang-zero1** [comment]
I will clean up the code some more, but the features are there and can be tested!

**Comment by Roang-zero1** [comment]
Ok I've found out there is still a performance problem with large bases, so I would hold of on releasing this branch until this is released.

**Comment by troelsbjerre** [comment]
Awesome work! I accidentally merged it to master, but now moved it back to the feature branch. I haven't had time for a proper test of it yet :(

About the big bases issue: One possible (major) change to the update logic is that we let go of the global dict of machines and their signals. Instead, updates would only happen around each player that want the signals shown (by re-scanning regularly). It would still be possible to cap the global number of updates per tick, and when its time for a new scan around a player, that scan would be the only computation that tick, so it might be fast enough.

Pro:
 - Refresh-rate of signals does not depend on size of base (!)
 - No need for event hooks for creation/deletion of signal-worthy entities

Con:
 - Update logic will be more complicated
 - Might be hard/infeasible to get it to work for far-views like train/radar view
 - Double calculation for nearby players
 - Performance depends on how many players have it enabled. Even though it is now an independent computation per player, it still has to be done everywhere, due to the lock-step requirement.

**Comment by Roang-zero1** [comment]
Sorry I did not elaborate enough it was just a quick message to make sure you do not release the version yet.
The problem is not with the mod update logic but the game functions for updating sprites. When there is a large number of sprites (>200k) changing a sprite or tint may take up to 11ms.
So changing it to be only around players would unfortunately not fix this if the player is in the newer parts of the base (higher rendering id).
I will file a bug report in the evening and link it here.

**Pull request merged**
